projet_python/urls.py
#Routes de racine
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('question.urls')),
]

user/urls.py
from django.shortcuts import render

from . import views

from django.urls import path, include
urlpatterns = [
    path('', views.ConnectPageView.as_view()),
]

question/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

#Toutes les tables de la BD
class Question(models.Model):
    
    titre = models.CharField(max_length=24, verbose_name="Titre de la question")
    texte = models.TextField(null=True, verbose_name="Question")
    #oneToOneField si relation 1-1
    class Meta:
        verbose_name = "Question"
        ordering = ['titre']
    
    def __str__(self):
        return self.titre

class Reponse(models.Model):
    
    reponse = models.TextField(null=True, verbose_name="réponse")

    class Meta:
        verbose_name = "Réponse"
    
    def __str__(self):
        return self.reponse

class QuestionReponse(models.Model):

    question = models.ForeignKey('Question', on_delete=models.CASCADE, null=False)
    reponse = models.ForeignKey('Reponse', on_delete=models.CASCADE, null=False)
    class Meta:
        verbose_name = "question et réponse"
        ordering = ['question']
    
    def __str__(self):
        return str(self.reponse)

class QuestionDuJour(models.Model):
    
    question = models.ForeignKey('Question', on_delete=models.CASCADE, null=False)
    date = models.DateField(auto_now_add=True, unique=True)

    class Meta:
        verbose_name = "question du jour"
        ordering = ['date']
    
    def __str__(self):
        return str(self.question)

class Choix(models.Model):
    
    question_reponse = models.ForeignKey('QuestionReponse', on_delete=models.CASCADE, null=False)
    user = models.ForeignKey('UserExtra', on_delete=models.CASCADE, null=False)
    date = models.DateField(auto_now_add=True)

    #en requete possibilite de faire : c.user.nom
    #oneToOneField si  relation 1-1
    class Meta:
        verbose_name = "choix"
        ordering = ['user']
        unique_together = ("question_reponse", "user")
    
    def __str__(self):
        return str(self.question_reponse)

class UserExtra(models.Model):
    SEXES = (
        ('F', 'Femme'),
        ('M', 'Homme')
    )
    INTERESSE = (
        ('F', 'Femme'),
        ('M', 'Homme'),
        ('T','Tout')
    )
 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100, verbose_name="Nom")
    prenom = models.CharField(max_length=100, verbose_name="Prénom")
    mail = models.CharField(max_length=100, verbose_name="Mail")
    age = models.IntegerField(verbose_name="Age", validators=[MaxValueValidator(100), MinValueValidator(15)])
    sexe = models.CharField(max_length=5, verbose_name="Sexe", choices=SEXES)
    interesse_par = models.CharField(max_length=5, verbose_name="Interessé par ", choices=INTERESSE)
    age_min_voulu = models.IntegerField(verbose_name="Age minimal voulu", validators=[MaxValueValidator(100), MinValueValidator(15)])
    age_max_voulu = models.IntegerField(verbose_name="Age maximal voulu", validators=[MaxValueValidator(100), MinValueValidator(15)])

    #accéder à la liste des choix d'un user : user.choix_set.all()
    class Meta:
        verbose_name = "utilisateur"
    
    def __str__(self):
        return self.nom

user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    
    nom = models.CharField(max_length=100, verbose_name="Nom utilisateur")
    prenom = models.CharField(max_length=100, verbose_name="Prénom utilisateur")
    mdp = models.CharField(max_length=24, verbose_name="Mot de passe")
    mail = models.CharField(max_length=100, verbose_name="Mail")
    age = models.IntegerField(verbose_name="Age")
    #photo = models.ImageField(upload_to='static/photos')
    
    #accéder à la liste des choix d'un user : user.choix_set.all()
    class Meta:
        verbose_name = "utilisateur"
    
    def __str__(self):
        return self.nom

templates/accounts/inscription.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h2 class="text-center">Inscription</h2>
    </div>
    <div class="card-body">
        <form method="POST" class="as_p">
            {% csrf_token %}
            <label for="id_username">Username :</label>
            <div class="form-group">
                {{ userform.username }}
            </div>
            <div class="row">
                <div class="col">
                    <label for="id_password1">Mot de Passe :</label>
                    <div class="form-group">
                        {{ userform.password1 }}
                    </div>
                </div>
                <div class="col">
                    <label for="id_password2">Confirmation :</label>
                    <div class="form-group">
                        {{ userform.password2 }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="id_nom">Nom :</label>
                    <div class="form-group">
                        {{ extraform.nom }}
                    </div>
                </div>
                <div class="col">
                    <label for="id_prenom">Prenom :</label>
                    <div class="form-group">
                        {{ extraform.prenom }}
                    </div>
                </div>
            </div>
            <label for="id_mail">Mail :</label>
            <div class="form-group">
                {{ extraform.mail }}
            </div>
            <div class="row">
                <div class="col">
                    <label for="id_age">Age :</label>
                    <div class="form-group">
                        {{ extraform.age }}
                    </div>
                </div>
                <div class="col">
                    <label for="id_sexe">Sexe :</label>
                    <div class="form-group">
                        {{ extraform.sexe }}
                    </div>
                </div>
                <div class="col">
                    <label for="id_interesse_par">Intéressé par :</label>
                    <div class="form-group">
                        {{ extraform.interesse_par }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="id_age_min_voulu">Age Minimal Voulu :</label>
                    <div class="form-group">
                        {{ extraform.age_min_voulu }}
                    </div>
                </div>
                <div class="col">
                    <label for="id_age_max_voulu">Age Maximal Voulu :</label>
                    <div class="form-group">
                        {{ extraform.age_max_voulu }}
                    </div>
                </div>
            </div>
            </div>
            <button type="submit" class="btn btn-primary">Inscription</button>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="card py-4 h-100">
        <h2 class="text-center">Login</h2>
        <div class="card-body">
            <form method="POST" class="as_p">
                {% csrf_token %}
                <label for="id_username">Nom d'utilisateur :</label>
                <div class="form-group">
                    {{ form.username }}
                </div>
                <label for="id_password">Mot de Passe :</label>
                <div class="form-group">
                    {{ form.password }}
                </div>
                <button type="submit" class="btn btn-primary">Connexion</button>
            </form>
            <hr>
            <div class="text-center">
                <a href="{% url 'inscription' %}">Inscription</a>
            </div>
        </div>
</div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Vous êtes désormais déconnecté</h1>
    <br>
    <div class="text-center">
        <a href="{% url 'index' %}">
            <button class="btn btn-primary">Retour à l'accueil</button>
        </a>
    </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="card py-4 h-100">
        <h2 class="text-center">Profil</h2>
        <div class="card-body">
            <div class="form-group">
                <label for="id_username">Username :</label>
                <div id="id_username">{{info.prenom}}</div>
            </div>
            <div class="form-group">
                    <label for="id_nom">Nom :</label>
                    <div id="id_nom">{{info.nom}}</div>
            </div>
            <div class="form-group">
                <label for="id_prenom">Prenom :</label>
                <div id="id_prenom">{{info.prenom}}</div>
            </div>
            <div class="form-group">
                <label for="id_age">Age :</label>
                <div id="id_age">{{info.age}}</div>
            </div>
            <div class="form-group">
                <label for="id_mail">Mail :</label>
                <div id="id_mail">{{info.mail}}</div>
            </div>
        </div>
</div>
{% endblock %}